<?php

use Illuminate\Routing\Route;

return [
    /**
     * Output path for the file generated by the publish command.
     * Provided as a config option for conveniences sake rather than a command arg.
     *
     */
    'outputPath' => resource_path('routes.json'),

    /**
     * Provide a list of flags utilized by json_encode for the serialized output.
     * See https://www.php.net/manual/en/function.json-encode.php argument 2 - "flags".
     *
     */
    'outputJsonFlags' => JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,

    /**
     * Whether to skip routes that don't define a name. If set false,
     * an Exception will be thrown when attempting to publish a route that has no name.
     *
     */
    'skipNameless' => true,

    /**
     * Define how the extra field of the serialized output is gathered.
     *
     * If false, the extra field is omitted.
     *
     * If a closure, an instance of  Illuminate\Routing\Route will be passed as the 1st argument.
     * This closure expects a return value of an array. See README for more details.
     *
     */
    'generateExtra' => false,

    /**
     *  Routes that should be included in the output.
     *
     *  Accepts either Nonetallt\Laravel\Route\Publish\Contract\RouteFilter or a closure that returns
     *  a bool value to determine if the Route should be filtered.
     *
     */
    'includeFilters' => [
        new Nonetallt\Laravel\Route\Publish\Filter\EverythingFilter()
    ],

    /**
     * Routes that should be excluded from the output.
     *
     * Excluded routes take precedence over included ones.
     *
     */
    'excludeFilters' => [
        function(Route $route) : bool {
            return false;
        }
    ]
];
